# Generated by Django 4.1.1 on 2022-12-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
