databases:
  - name: cycom
    databaseName: cycom
    user: cycom_user
    plan: free

services:
  - type: web
    name: cycom
    env: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn cycom.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cycom
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
